# Generated by Django 2.2a1 on 2019-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190203_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favourites',
            field=models.BooleanField(default=True),
        ),
    ]
