# Generated by Django 2.2a1 on 2019-02-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190203_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favourites',
            field=models.BooleanField(default=False),
        ),
    ]
