# Generated by Django 2.2a1 on 2019-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190203_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favourites',
            field=models.BooleanField(),
        ),
    ]
