# Generated by Django 2.2a1 on 2019-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190203_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favourte',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favouritte',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
