# Generated by Django 2.2a1 on 2019-02-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20190203_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favouritte',
            field=models.BooleanField(default='True'),
        ),
    ]
