# Generated by Django 2.2a1 on 2019-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190203_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favouritte',
            field=models.BooleanField(default='1'),
        ),
    ]
