# Generated by Django 2.2a1 on 2019-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20190203_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favouritte',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
