# Generated by Django 2.2a1 on 2019-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20190205_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='song',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
    ]
