# Generated by Django 2.2a1 on 2019-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20190205_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_select',
            field=models.BooleanField(default='False'),
        ),
    ]
