# Generated by Django 2.2a1 on 2019-02-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20190205_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_select',
            field=models.BooleanField(default='t'),
        ),
    ]
