# Generated by Django 2.2a1 on 2019-02-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20190205_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
    ]
