# Generated by Django 2.2a1 on 2019-03-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20190206_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_select',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
